export var affirmations = [
"Never give up!",
"You can't have a rainbow without a little rain",
"Every cloud has a silver lining" ,
"Remember- your body is a temple!",
"Keep going, you got this!",
"Believe in yourself" ,
"Be confident" ,
"Every day is a new beginning",
"It's just a bad day- not a bad life", 
"You can do it." ,
"Practice makes perfect", 
"Be true to who you are",
"When one chapter ends, another begins",
"Mistakes are just an apprenticeship to achievement" ,
"You are in charge of your happiness" ,
"Seize every moment",
"Live, love, laugh" ,
"Surround yourself with happiness",
"Dance in the eye of the storm",
"You're indesctructible",
"Inhale confidence, exhale fear",
"Try not to sweat the small stuff" ,
"The little things can make a big difference",
"You're not alone",
"You deserve the best",
"There's no time like the present" ,
"Find joy and pleasure in the most simple things in life",
"You are the architect of your life; You build its foundation and choose its contents",
"Learn from yesterday live for today"
];